### ISSUE TITLE
Consider non-MetaMask injected connector support

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/web3-react#350]
Support for injected connectors other than metamask should be considered (e.g. trust).

This could be accomplished via a new connector which is more generic and handles edge cases/non-standard behavior better, or potentially this logic could be put in the metamask connector itself

**Comment by remon-nashid** [comment]
Trust wallet works fine with the `injected` connector as far as I can tell.

**Comment by NoahZinsmeister** [comment]
yeah, in that same vein it's possible that the best thing to do here is just officially deprecate non-eip1193-compliant injected connectors

**Comment by talentlessguy** [comment]
Since it's already implemented, I'll close this issue

https://github.com/Uniswap/web3-react/tree/main/packages/eip1193
