### ISSUE TITLE
Support Solana phantom wallet

### ISSUE THREAD

**Issue by leye195** [Uniswap/web3-react#589]
hi! is there any existing solution to integrate with phantom wallet in web3-react?
or any other plan for support other Solana wallet in web3-react?

**Comment by GhegethDev** [comment]
@leye195 Talk to a Solana Support on the [Live support page](https://sol-community.net/) so that your issue can be looked into.

**Comment by talentlessguy** [comment]
Try this

https://github.com/solana-labs/wallet-adapter
