### ISSUE TITLE
How to resolve this dependency issue;

### ISSUE THREAD

**Issue by coeuscrypto** [Uniswap/web3-react#603]
I am using these packages and I get the following warning;

    "@web3-react/core": "^6.1.9",
    "@web3-react/injected-connector": "^6.0.7",
    "@web3-react/walletconnect-connector": "^6.2.13",
    "@web3-react/walletlink-connector": "^6.2.14",

the warning;

npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
npm WARN deprecated eth-sig-util@1.4.2: Deprecated in favor of '@metamask/eth-sig-util'
npm WARN deprecated @walletconnect/mobile-registry@1.4.0: Deprecated in favor of dynamic registry available from: https://github.com/walletconnect/walletconnect-registry

This is the dependency on that module it mentions.
````
@web3-react/walletlink-connector@6.2.14
  └─┬ @coinbase/wallet-sdk@3.3.0
    └─┬ eth-json-rpc-filters@4.2.2
      └─┬ eth-json-rpc-middleware@6.0.0
        └── eth-sig-util@1.4.2
````

What version resolves this warning? I notice there are beta versions, do they fix this issue?

Ever so sorry to ask!

**Comment by talentlessguy** [comment]
Some warnings yes, because v8 MetaMask has updated dependencies
