### ISSUE TITLE
Question: What is the purpose of implementing the Gnosis Safe Connector if WalletConnect can handle Gnosis Safe?

### ISSUE THREAD

**Issue by 0xD4V1NC1** [Uniswap/web3-react#610]
unsure how to add the question label... not a real issue

**Comment by vm** [comment]
The Gnosis Safe connector is for use within a safe context. See here: https://help.gnosis-safe.io/en/articles/4022022-what-are-safe-apps

**Comment by 0xD4V1NC1** [comment]
> The Gnosis Safe connector is for use within a safe context. See here: https://help.gnosis-safe.io/en/articles/4022022-what-are-safe-apps

ahh okay. Thank you
