### ISSUE TITLE
Getting This Error

### ISSUE THREAD

**Issue by shikhar360** [Uniswap/web3-react#616]
inpage.js:1 MetaMask: The event 'close' is deprecated and may be removed in the future. Please use 'disconnect' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193#disconnect
_warnOfDeprecation @ inpage.js:1
inpage.js:1 MetaMask: The event 'networkChanged' is deprecated and may be removed in the future. Use 'chainChanged' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193#chainchanged
_warnOfDeprecation @ inpage.js:1
inpage.js:1 MetaMask: 'ethereum.send(...)' is deprecated and may be removed in the future. Please use 'ethereum.sendAsync(...)' or 'ethereum.request(...)' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193

**Comment by IrfanPatelDev** [comment]
I am also facing this issue, Please help if you found any solution.
