### ISSUE TITLE
Cannot Connecting with Wallet Connect : Please Guide

### ISSUE THREAD

**Issue by Anishali2** [Uniswap/web3-react#676]
![image](https://user-images.githubusercontent.com/105014311/192214420-d430ad69-7ab2-46be-9165-8c087e3a737e.png)
This is my connector and I am connecting my connector with web3-react using
 
<Web3Provider connector={connector} libraryName={'ether.js'}
![image](https://user-images.githubusercontent.com/105014311/192219986-9fe48493-db07-43a1-8170-b9a7f5f51488.png)
It shows me error

**Comment by berkaycirak** [comment]
connectors that you are passing into web3provider components must be an array, try that

**Comment by Anishali2** [comment]
> connectors that you are passing into web3provider components must be an array, try that

I am using "web3-react" https://www.npmjs.com/package/web3-react/v/5.0.5  . It cannot take array

**Comment by JoeyKhd** [comment]
I suggest you use the latest beta version and refer to the examples in : https://github.com/Uniswap/web3-react/tree/main/packages/example-next

**Comment by Anishali2** [comment]
> I suggest you use the latest beta version and refer to the examples in : https://github.com/Uniswap/web3-react/tree/main/packages/example-next

@JoeyKhd  Brother I configured my project in web3-react and my client ask me to add walletconnect library into it but i cannot find any solution .web3-react provide me WalletConnectConnector but I don't know how to pass params of it

```
import { Connectors } from 'web3-react';
const {  WalletConnectConnector } = Connectors;

const wallet = new WalletConnectConnector({
  api,???
bridge,???
defaultNetwork,???
supportedNetworkURLs ???
})

**Comment by JoeyKhd** [comment]
5.0.5 is 3 years old, I strongly suggest you upgrade to ^8.0.0 so you can follow the latest examples as explained in the previous message.

**Comment by Anishali2** [comment]
You are right Thanks for your help
