### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by davidthomasparks** [Uniswap/web3-react#682]
Is this repository still being maintained? I saw ownership was transferred to Uniswap but have not seen a publish in over 2 months. The backbone of our app relies on this repository so it would be great to know it's still being watched/ worked on. Thanks!

**Comment by cmcewen** [comment]
Hi @davidthomasparks - we are maintaining this but have been focused on a few other things recently. Is there anything specifically that you're looking for or blocked on?

**Comment by davidthomasparks** [comment]
Hey @cmcewen, nothing in particular. However knowing that you guys are still here is good enough for me! Thanks.
