### ISSUE TITLE
Nextjs 13 Server Component Support

### ISSUE THREAD

**Issue by davidthomasparks** [Uniswap/web3-react#693]
Next.js has just released version 13, which includes support for React Server components.

However, since web3-react needs to wrap the entire layout in a Web3 provider, you need to opt into using a client component with `use client` essentially nullifying the use of server components downstream in the entire app. 

Are there any plans to support not needing a provider for the application, or can you shed some light on possible workarounds to make use of react server components without having to wrap my entire app in a client component due to the Web3ReactProvider?

**Comment by shlokkhemani** [comment]
hey! how are you solving this?
