### ISSUE TITLE
[Gnosis safe] connection not working

### ISSUE THREAD

**Issue by jeanbenoit-richez** [Uniswap/web3-react#733]
Configuration: 
**nodejs:** v18.12.1
**next.js:** v12.1.5
**react:** v18.2.0
**web3-react/core:** 8.0.35-beta.0
**web3-react/gnosis:** 8.0.7-beta.0

Hi,
I'm trying to add gnosis connection to my app through [Gnosis App](https://app.safe.global/).
Currently every connections I implemented are working (metamask and wallet connect) so the problem is not coming from the way I implemented web3-react/gnosis-safe module.

The problem is when i'm trying to connect to my App with gnosis sage interface (iframe of my App in Gnosis App) something weird is happening: in console I see that `web3-react/gnosis` has succeed to connect to gnosis safe context but `web3-react/core` seems to not understanding that.
To verify this I cloned the `web3-react/gnosis` package then add some console.log in activate() function.
this is my connector:
``` 
import { initializeConnector } from "@web3-react/core";
import { GnosisSafe } from "./gnosis";
export const [gnosisSafe, hooks] = initializeConnector<GnosisSafe>((actions) => new GnosisSafe({ actions }));
```
My logging function:
```
const onActivating = useCallback(async () => {
    try{
      console.log(connector)
      setIsActivating(true);
      await connector.activate();
      console.log('test')
      setIsActivating(false);
      onSuccess();
    }catch(err){
      console.log(err)
    }
  }, [connector, onSuccess]);
```
As you can see in console the connector is GnosisSafe and i got the right chainId (100) and i'm connected to the right adresse.
<img width="496" alt="Capture d’écran 2022-12-26 à 14 39 06" src="https://user-images.githubusercontent.com/119856665/209554937-8886a57f-37e2-4193-8bac-86802601ebdf.png">
But i don't have any address or provider when I use useWeb3React.

Thanks for help.

**Comment by niZmosis** [comment]
If you're only using gnosis, you don't need to use useWeb3React. If you do want to use it, you need to use the useSelected* hooks and pass the connector into it. 

const { useSelectedChainId } = useWeb3React()

const chainId = useSelectedChainId(gnosis)



I'm on my phone so I can't do a very good example but that will get you in the right direction. I have a big PR pending that will make using the Web3ReactProvider a lot easier. If you go to my branch, I made a readme for migrating and it shows how to do it with the useSelected* hooks and it explains how the Web3ReactProvider works. 

As of right now the hooks from the useWeb3React, are taking the hooks from the priority connector. The priority connector is the first "active" connector that you passed into the Web3React Provider "connectors" prop. The PR will let you select what connector is using the hooks at any given time.

**Comment by jeanbenoit-richez** [comment]
@niZmosis Thanks you very much.
your docs is really much better than the current one :)
