### ISSUE TITLE
Zustand warnings

### ISSUE THREAD

**Issue by glowx** [Uniswap/web3-react#743]
Zustand issued these warnings:

```
[DEPRECATED] default export is deprecated, instead import { create } from'zustand'
```

```
bundle.js:181307 [DEPRECATED] Passing a vanilla store will be unsupported in the future version. Please use `import { useStore } from "zustand"` to use the vanilla store in React.
```

Code syntax needs updating.

![Screen Shot 2023-01-26 at 03 40 14](https://user-images.githubusercontent.com/1852808/214671576-4d6073c4-954d-4af4-8870-4d676bb21f86.png)

**Comment by niZmosis** [comment]
Web3React is using Zustand 4.0, seems like you may have a newer version installed. Downgrade to 4.0 and it will go away.

**Comment by shunz19** [comment]
I ran `yarn add zustand@4.0.0-rc.0` and the warnings are still there.

**Comment by glowx** [comment]
@niZmosis In yarn.lock I only have one zustand version: `zustand@^4.0.0-rc.0`

**Comment by niZmosis** [comment]
I updated Zustand in my [PR](https://github.com/Uniswap/web3-react/pull/730)

**Comment by grabbou** [comment]
This is already fixed in master. Will be released soon.

**Comment by zzmp** [comment]
This needs to be updated in https://github.com/Uniswap/web3-react/blob/main/packages/core/src/hooks.ts#L7

**Comment by grabbou** [comment]
@zzmp was correct, I did fix `store` deprecation, but other warnings were still there. Either way, this is now fixed, thanks @zzmp for prompt fix!
