### ISSUE TITLE
Unable to install wallectconnect -v2

### ISSUE THREAD

**Issue by deutschefi** [Uniswap/web3-react#775]
Module not found: Can't resolve '@web3-react/walletconnect-v2'

**Comment by zzmp** [comment]
We haven't yet published v2 to npm, but plan to do so soon.

**Comment by daniimendes22** [comment]
Is there any prediction when they will publish?

**Comment by deutschefi** [comment]
Why no auto publish?

**Comment by felcl** [comment]
> 我们尚未将 v2 发布到 npm，但计划尽快发布。
Hello, when can I release it?

**Comment by felcl** [comment]
> 我们尚未将 v2 发布到 npm，但计划尽早发布。

Hello, when can you release it?

**Comment by Christopher-Stevers** [comment]
When is it going to be released? wallet-connect 1 isn't working for our app, so we'd really like to upgrade to v2. Let me know if I can help in any way to get it published, or if you have a workaround to use the code directly from github.

**Comment by grabbou** [comment]
A new package `walletconnect-v2` will be released to npm later today, you can check it out for an early preview. We haven't tested it yet, so it's not considered production ready just yet. We will now begin testing at Uniswap main application and fix any issues that happen in the meantime.

If you run across any, feel free to report too!

**Comment by deutschefi** [comment]
did this come?
