### ISSUE TITLE
Gnosis Safe error on activate: "NoSafeContext: The app is loaded outside safe context"

### ISSUE THREAD

**Issue by BenAzlay** [Uniswap/web3-react#858]
I am initializing the Gnosis Safe connector like this:
```JavaScript
export const [gnosisSafe, gnosisSafeHooks] = initializeConnector((actions) => new GnosisSafe({ actions }))
```
And then, on the click of a button, I'm activating it like this:
```JS
await connector.activate().catch(e => console.error("activate ERROR", e));
```
That's where this error is thrown:
```
shim.js:1 activateWallet activate ERROR NoSafeContext: The app is loaded outside safe context
    at GnosisSafe.<anonymous> (http://localhost:3000/static/js/bundle.js:291427:33)
    at Generator.next (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:291342:67
    at new Promise (<anonymous>)
    at __webpack_modules__../node_modules/@web3-react/gnosis-safe/dist/index.js.__awaiter (http://localhost:3000/static/js/bundle.js:291324:10)
    at GnosisSafe.activate (http://localhost:3000/static/js/bundle.js:291426:12)
    at activateWallet (http://localhost:3000/static/js/bundle.js:16292:23)
    at onClick (http://localhost:3000/static/js/bundle.js:12863:22)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:174153:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:174197:20)
```
How do I create a "safe context"? I've looked up [the Gnosis Safe SDK documentation](https://docs.safe.global/learn/safe-apps/build) and it doesn't mention this at all.

**Comment by BowgartField** [comment]
Hi @BenAzlay ,
A Gnosis Safe context is created when you run the app inside a iframe from Gnosis-safe website.

So basically you need to go to [Gnosis-safe website](https://app.safe.global/apps/), create an app with your url.
Then it will run your app inside an GnosisSafeContext.
Tell me if it works ?

Because before I succeed to make it works but until web3-react update it seems to be broken.

**Comment by BowgartField** [comment]
Hi @NoahZinsmeister,
There is a problem with one of the update (I cannot say with version is responsible of the bug).
The package [@web3-react/gnosis-safe](https://github.com/Uniswap/web3-react/blob/main/packages/gnosis-safe), cannot detect the gnosis safe context and thow this error: 
![Capture d’écran 2023-07-21 à 10 08 52](https://github.com/Uniswap/web3-react/assets/13118844/ad48dd02-ce46-4944-b578-a0df960e2476)

But the SafeContext really exsists as you can see here:
![Capture d’écran 2023-07-21 à 10 10 09](https://github.com/Uniswap/web3-react/assets/13118844/3d2a919b-0161-477e-a1d8-ce3f342c991f)
I used `@gnosis.pm/safe-apps-sdk` package to detect if i'm in a SafeContext or not, like this:
```
const fetchIfGnosis = async () => {
      try {
        const gnosisSdk = new SafeAppsSDK()
        const test = await gnosisSdk.safe.getInfo();
        console.log(test)
        setGnosisDisabled(false);
      } catch (e) {
        console.log('Gnosis Safe is not detected', e);
      }
    }

```


Thanks :)

**Comment by BenAzlay** [comment]
@BowgartField I'm indeed running my dApp inside a Gnosis Safe context, but still, as you said, web3-react doesn't detect it.
@NoahZinsmeister Any update on this?

**Comment by BenAzlay** [comment]
The fact of the matter is that app.uniswap.org does NOT show a separate option for Gnosis Safe, and that their own [web-react example](https://web3-react-mu.vercel.app/) does NOT work for Gnosis Safe. Therefore I will simply remove the Gnosis Safe option from my dApp (Safe users will be able to connect using WalletConnect).

**Comment by BowgartField** [comment]
I found a solution.
You need to create your own gnosis connector.
