### ISSUE TITLE
Unable to use web3-react/core due to deprecated dependency

### ISSUE THREAD

**Issue by sophie-pan** [Uniswap/web3-react#871]
Hello,
I was trying to connect to a metamask wallet using `@web3-react/core` and `@web3-react/metamask`. But the console keep prompting the following message.
[DEPRECATED] Use `createWithEqualityFn` from 'zustand/traditional'. https://github.com/pmndrs/zustand/discussions/1937

**Comment by Lupul** [comment]
I get the same messages in console
